name: flutter_dynamic_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dynamic_widget:
    path: ../dynamic_widget
  flutter:
    sdk: flutter
  provider: ^6.0.5
  json_annotation: ^4.8.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  freezed: ^2.3.4
  retrofit: ^4.0.1
  flutter_simple_dependency_injection: ^2.0.0
  retrofit_generator: ^7.0.1
  text_scroll: ^0.2.0
  blobs: ^2.0.0
  form_builder_validators: ^9.0.0
  adaptive_dialog: ^1.9.0-no-macos.2
  carousel_slider: ^4.2.1
  adaptive_navbar: ^0.0.3
  page_transition: ^2.0.9
  intl: ^0.18.0
  device_preview: ^1.1.0
  uuid: ^3.0.7
  collection: ^1.17.1
  flex_color_picker: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
      - assets/
