// <auto-generated />
using System;
using DynamicStore.Api.Data.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DynamicStore.Api.Data.PostgreSql.Migrations
{
    [DbContext(typeof(EfContext))]
    partial class EfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_id");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid")
                        .HasColumnName("products_id");

                    b.HasKey("CategoriesId", "ProductsId")
                        .HasName("pk_category_product");

                    b.HasIndex("ProductsId")
                        .HasDatabaseName("ix_category_product_products_id");

                    b.ToTable("category_product", "public");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Advertising", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Ид картинки");

                    b.Property<Guid?>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key")
                        .HasComment("Ключ");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование рекламы");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route")
                        .HasComment("Путь");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id")
                        .HasComment("Ид магазина");

                    b.HasKey("Id")
                        .HasName("pk_advertisements");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_advertisements_file_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_advertisements_shop_id");

                    b.ToTable("advertisements", "public");

                    b.HasComment("Рекламы");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code")
                        .HasComment("Код категории");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание категории");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Ид картинки");

                    b.Property<Guid?>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key")
                        .HasComment("Ключ");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование категории");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_file_id");

                    b.ToTable("categories", "public");

                    b.HasComment("Категории товаров");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_files_product_id");

                    b.ToTable("files", "public");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from")
                        .HasComment("Дата активации дизайна");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Признак удаленности");

                    b.Property<string>("LayoutDesign")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_design")
                        .HasComment("Дизайн страницы");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id")
                        .HasComment("Ид магазина");

                    b.HasKey("Id")
                        .HasName("pk_layouts");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_layouts_shop_id");

                    b.ToTable("layouts", "public");

                    b.HasComment("Дизайны страничек магазинов");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsPayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_payed")
                        .HasComment("Оплачен ли заказ");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Количество товаров");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price")
                        .HasComment("Общая стоимость");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Пользователь");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", "public");

                    b.HasComment("Заказы");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id")
                        .HasComment("Ид заказа");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id")
                        .HasComment("Ид товара");

                    b.HasKey("Id")
                        .HasName("pk_order_products");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_products_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_products_product_id");

                    b.ToTable("order_products", "public");

                    b.HasComment("Товары из заказов");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание товара");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование товара");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price")
                        .HasComment("Цена товара");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id")
                        .HasComment("Ид магазина");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_products_shop_id");

                    b.ToTable("products", "public");

                    b.HasComment("Товары");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Ид картинки");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование магазина");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id")
                        .HasComment("Ид владельца");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_shops_file_id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_shops_owner_id");

                    b.ToTable("shops", "public");

                    b.HasComment("Магазины");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_in(md5(random()::text || clock_timestamp()::text)::cstring)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasComment("Email");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Ид картинки");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Имя пользователя");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasComment("Хэш пароля");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id")
                        .HasComment("Ид магазина");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_file_id");

                    b.HasIndex("ShopId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_shop_id");

                    b.ToTable("users", "public");

                    b.HasComment("Пользователи");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_product_categories_categories_id");

                    b.HasOne("DynamicStore.Api.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_product_products_products_id");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Advertising", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.File", "File")
                        .WithOne("Advertising")
                        .HasForeignKey("DynamicStore.Api.Core.Entities.Advertising", "FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_advertisements_files_file_id");

                    b.HasOne("DynamicStore.Api.Core.Entities.Shop", "Shop")
                        .WithMany("Advertisings")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_advertisements_shops_shop_id");

                    b.Navigation("File");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Category", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.File", "File")
                        .WithOne("Category")
                        .HasForeignKey("DynamicStore.Api.Core.Entities.Category", "FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.File", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.Product", "Product")
                        .WithMany("Files")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_files_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Layout", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.Shop", "Shop")
                        .WithMany("Layouts")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_layouts_shops_shop_id");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Order", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.OrderProduct", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_products_orders_order_id");

                    b.HasOne("DynamicStore.Api.Core.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_products_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Product", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_shops_shop_id");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Shop", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.File", "File")
                        .WithOne("Shop")
                        .HasForeignKey("DynamicStore.Api.Core.Entities.Shop", "FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shops_files_file_id");

                    b.HasOne("DynamicStore.Api.Core.Entities.User", "Owner")
                        .WithOne()
                        .HasForeignKey("DynamicStore.Api.Core.Entities.Shop", "OwnerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("fk_shops_users_owner_id1");

                    b.Navigation("File");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.User", b =>
                {
                    b.HasOne("DynamicStore.Api.Core.Entities.File", "File")
                        .WithOne("User")
                        .HasForeignKey("DynamicStore.Api.Core.Entities.User", "FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_files_file_id");

                    b.HasOne("DynamicStore.Api.Core.Entities.Shop", "Shop")
                        .WithOne()
                        .HasForeignKey("DynamicStore.Api.Core.Entities.User", "ShopId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .HasConstraintName("fk_users_shops_shop_id");

                    b.Navigation("File");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.File", b =>
                {
                    b.Navigation("Advertising");

                    b.Navigation("Category");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Product", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.Shop", b =>
                {
                    b.Navigation("Advertisings");

                    b.Navigation("Layouts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DynamicStore.Api.Core.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
